In [ ]:
URL_WTA = "https://raw.githubusercontent.com/ryantjx/tennis-match-data/main/wta-matches.json.gz"

In [3]:
import polars as pl

BASE_URL = (
    "https://github.com/ryantjx/tennis-match-data/releases/download/"
    "data-v3-20260724T164801Z"
)

df = pl.read_parquet(f"{BASE_URL}/fixtures.parquet")
df

shape: (15, 20)
┌──────┬──────────────┬──────────────┬──────────────┬───┬─────────┬───────┬─────────┬──────────────┐
│ date ┆ match_id     ┆ tournament_i ┆ tournament_n ┆ … ┆ status  ┆ score ┆ best_of ┆ source       │
│ ---  ┆ ---          ┆ d            ┆ ame          ┆   ┆ ---     ┆ ---   ┆ ---     ┆ ---          │
│ date ┆ str          ┆ ---          ┆ ---          ┆   ┆ str     ┆ str   ┆ i8      ┆ list[str]    │
│      ┆              ┆ str          ┆ str          ┆   ┆         ┆       ┆         ┆              │
╞══════╪══════════════╪══════════════╪══════════════╪═══╪═════════╪═══════╪═════════╪══════════════╡
│ null ┆ match_498a77 ┆ tournament_a ┆ Estoril Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 0de3c69a464d ┆ tp_2026_3910 ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 63a676       ┆ c539d0…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_d68e05 ┆ tournament_a ┆ Estoril Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 02e36d9076f3 ┆ tp_2026_3910 ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 01d53e       ┆ c539d0…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_162557 ┆ tournament_a ┆ Estoril Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ eac9e31a60ac ┆ tp_2026_3910 ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ ecde68       ┆ c539d0…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_171ff2 ┆ tournament_a ┆ Estoril Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 70c94cc00afb ┆ tp_2026_3910 ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 1ad853       ┆ c539d0…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_634efb ┆ tournament_a ┆ Generali     ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 9e330c5dc19a ┆ tp_2026_6736 ┆ Open         ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 59feb0       ┆ f82311…      ┆ Kitzbühel    ┆   ┆         ┆       ┆         ┆              │
│ …    ┆ …            ┆ …            ┆ …            ┆ … ┆ …       ┆ …     ┆ …       ┆ …            │
│ null ┆ match_dbf537 ┆ tournament_w ┆ Hamburg Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 0480f38dd176 ┆ ta_2026_dbbc ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 07fdd0       ┆ aaec7f…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_38c175 ┆ tournament_w ┆ Hamburg Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 75fc22aa2c80 ┆ ta_2026_dbbc ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 0a623a       ┆ aaec7f…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_63f279 ┆ tournament_w ┆ Hamburg Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 9a2f9ed243a1 ┆ ta_2026_dbbc ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ bf1bf0       ┆ aaec7f…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_b80f3d ┆ tournament_w ┆ Hamburg Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ 23f8c1307e08 ┆ ta_2026_dbbc ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 1ee925       ┆ aaec7f…      ┆              ┆   ┆         ┆       ┆         ┆              │
│ null ┆ match_d13653 ┆ tournament_w ┆ Hamburg Open ┆ … ┆ fixture ┆ null  ┆ 3       ┆ ["wikimedia" │
│      ┆ b9ad60daadd1 ┆ ta_2026_dbbc ┆              ┆   ┆         ┆       ┆         ┆ ]            │
│      ┆ 1a371e       ┆ aaec7f…      ┆              ┆   ┆         ┆       ┆         ┆              │
└──────┴──────────────┴──────────────┴──────────────┴───┴─────────┴───────┴─────────┴──────────────┘

In [ ]:
# Example 2: Scatter plot - exploring winner vs loser rankings
# Adjust column names based on your actual data structure

if "winner_rank" in df.columns and "loser_rank" in df.columns:
    scatter_data = df.select([
        pl.col("winner_rank").cast(pl.Int64),
        pl.col("loser_rank").cast(pl.Int64)
    ]).drop_nulls().sample(min(5000, df.height))  # Sample for performance
    
    scatter = alt.Chart(scatter_data.to_pandas()).mark_circle(opacity=0.3).encode(
        x=alt.X("winner_rank:Q", title="Winner Rank"),
        y=alt.Y("loser_rank:Q", title="Loser Rank"),
        tooltip=["winner_rank", "loser_rank"]
    ).properties(
        title="Winner Rank vs Loser Rank",
        width=500,
        height=400
    )
    scatter

In [ ]:
import altair as alt

# Example: Plot number of matches per year
# First, extract year from the date column (assuming there's a date column)
# Adjust column names based on your actual data

# Example 1: Simple bar chart of matches by year
if "date" in df.columns:
    chart_data = df.with_columns(
        pl.col("date").str.to_date().dt.year().alias("year")
    ).group_by("year").agg(pl.count()).sort("year")
    
    chart = alt.Chart(chart_data.to_pandas()).mark_bar().encode(
        x="year:O",
        y="count:Q",
        tooltip=["year", "count"]
    ).properties(
        title="Number of WTA Matches by Year"
    )
    chart
else:
    print("Available columns:", df.columns)

In [4]:
import polars as pl
import requests
import gzip
import io

# Download the compressed JSON file
URL_WTA = "https://raw.githubusercontent.com/ryantjx/tennis-match-data/main/wta-matches.json.gz"
response = requests.get(URL_WTA)
response.raise_for_status()

# Decompress and read the JSON
decompressed = gzip.decompress(response.content)
df = pl.read_json(io.BytesIO(decompressed))

# Display basic info about the dataset
print(f"Shape: {df.shape}")
print(f"\nColumns: {df.columns}")
df.head()

Shape: (1, 5)

Columns: ['filter', 'kind', 'match_count', 'matches', 'schema_version']

shape: (1, 5)
┌─────────────────┬───────────────┬─────────────┬─────────────────────────────────┬────────────────┐
│ filter          ┆ kind          ┆ match_count ┆ matches                         ┆ schema_version │
│ ---             ┆ ---           ┆ ---         ┆ ---                             ┆ ---            │
│ struct[2]       ┆ str           ┆ i64         ┆ list[struct[3]]                 ┆ i64            │
╞═════════════════╪═══════════════╪═════════════╪═════════════════════════════════╪════════════════╡
│ {["wta"],"wta"} ┆ match_extract ┆ 164299      ┆ [{{"singles","main","sackmann:… ┆ 2              │
└─────────────────┴───────────────┴─────────────┴─────────────────────────────────┴────────────────┘

In [8]:
# Let's unnest the event and match columns to see all fields
matches_full = matches_df.unnest("event").unnest("match")
print(f"Full matches shape: {matches_full.shape}")
print(f"\nAll columns: {matches_full.columns}")
matches_full.head()

Full matches shape: (164299, 20)

All columns: ['discipline', 'draw', 'id', 'level', 'name', 'start_date', 'surface', 'tour', 'year', 'bracket_slot', 'first_completed_observed_on', 'match_id', 'played_on', 'players', 'round', 'score', 'sources', 'status', 'winner_id', 'source_file']

shape: (5, 20)
┌────────────┬──────┬─────────────┬───────┬───┬─────────────┬───────────┬────────────┬─────────────┐
│ discipline ┆ draw ┆ id          ┆ level ┆ … ┆ sources     ┆ status    ┆ winner_id  ┆ source_file │
│ ---        ┆ ---  ┆ ---         ┆ ---   ┆   ┆ ---         ┆ ---       ┆ ---        ┆ ---         │
│ str        ┆ str  ┆ str         ┆ str   ┆   ┆ list[struct ┆ str       ┆ str        ┆ str         │
│            ┆      ┆             ┆       ┆   ┆ [2]]        ┆           ┆            ┆             │
╞════════════╪══════╪═════════════╪═══════╪═══╪═════════════╪═══════════╪════════════╪═════════════╡
│ singles    ┆ main ┆ sackmann:wt ┆ W     ┆ … ┆ [{"sackmann ┆ completed ┆ wta:200139 ┆ matches/wta │
│            ┆      ┆ a:1968-1226 ┆       ┆   ┆ ","1968-122 ┆           ┆            ┆ /1968/adela │
│            ┆      ┆             ┆       ┆   ┆ 6:1"}]      ┆           ┆            ┆ ide/main…   │
│ singles    ┆ main ┆ sackmann:wt ┆ W     ┆ … ┆ [{"sackmann ┆ completed ┆ wta:200203 ┆ matches/wta │
│            ┆      ┆ a:1968-1226 ┆       ┆   ┆ ","1968-122 ┆           ┆            ┆ /1968/adela │
│            ┆      ┆             ┆       ┆   ┆ 6:2"}]      ┆           ┆            ┆ ide/main…   │
│ singles    ┆ main ┆ sackmann:wt ┆ W     ┆ … ┆ [{"sackmann ┆ completed ┆ wta:200149 ┆ matches/wta │
│            ┆      ┆ a:1968-1226 ┆       ┆   ┆ ","1968-122 ┆           ┆            ┆ /1968/adela │
│            ┆      ┆             ┆       ┆   ┆ 6:3"}]      ┆           ┆            ┆ ide/main…   │
│ singles    ┆ main ┆ sackmann:wt ┆ W     ┆ … ┆ [{"sackmann ┆ completed ┆ wta:200168 ┆ matches/wta │
│            ┆      ┆ a:1968-1226 ┆       ┆   ┆ ","1968-122 ┆           ┆            ┆ /1968/adela │
│            ┆      ┆             ┆       ┆   ┆ 6:4"}]      ┆           ┆            ┆ ide/main…   │
│ singles    ┆ main ┆ sackmann:wt ┆ W     ┆ … ┆ [{"sackmann ┆ completed ┆ wta:200188 ┆ matches/wta │
│            ┆      ┆ a:1968-1226 ┆       ┆   ┆ ","1968-122 ┆           ┆            ┆ /1968/adela │
│            ┆      ┆             ┆       ┆   ┆ 6:5"}]      ┆           ┆            ┆ ide/main…   │
└────────────┴──────┴─────────────┴───────┴───┴─────────────┴───────────┴────────────┴─────────────┘

In [11]:
# 6. Date range of the dataset
print("=== Date Range ===")
# Filter out null dates
dates = matches_full.filter(pl.col("start_date").is_not_null())
print(f"Earliest match: {dates['start_date'].min()}")
print(f"Latest match: {dates['start_date'].max()}")

# 7. Sample of recent matches (2025-2026)
print("\n=== Recent Matches (2025-2026) ===")
recent = matches_full.filter(pl.col("year") >= 2025).select([
    "name", "start_date", "round", "surface", "status"
]).head(10)
print(recent)

=== Date Range ===
Earliest match: 1967-12-25
Latest match: 2026-05-25

=== Recent Matches (2025-2026) ===
shape: (10, 5)
┌───────────┬────────────┬───────┬─────────┬───────────┐
│ name      ┆ start_date ┆ round ┆ surface ┆ status    │
│ ---       ┆ ---        ┆ ---   ┆ ---     ┆ ---       │
│ str       ┆ str        ┆ str   ┆ str     ┆ str       │
╞═══════════╪════════════╪═══════╪═════════╪═══════════╡
│ Abu Dhabi ┆ 2025-02-03 ┆ F     ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ SF    ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ SF    ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ QF    ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ QF    ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ QF    ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ QF    ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ R16   ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ R16   ┆ Hard    ┆ completed │
│ Abu Dhabi ┆ 2025-02-03 ┆ R16   ┆ Hard    ┆ completed │
└───────────┴────────────┴───────┴─────────┴───────────┘

In [16]:
# First, let's explore the players column structure
print("Sample players data:")
sample_players = matches_full["players"].head(3)
for i, players in enumerate(sample_players):
    print(f"\nMatch {i+1}:")
    print(players)
    
# Check the struct field names
print("\n\nStruct field names in players column:")
print(matches_full["players"].dtype)

# Check sources structure
print("\n\nSources structure:")
print(matches_full["sources"].dtype)
print("\nSample sources:")
print(matches_full["sources"].head(3))

Sample players data:

Match 1:
shape: (2,)
Series: '' [struct[3]]
[
	{"INA","wta:200139","Lita Liem"}
	{"AUS","wta:200146","Cynthia Doerner"}
]

Match 2:
shape: (2,)
Series: '' [struct[3]]
[
	{"AUS","wta:200203","Vicki Lancaster Kerr"}
	{"AUS","wta:216624","Barbara Walsh"}
]

Match 3:
shape: (2,)
Series: '' [struct[3]]
[
	{"AUS","wta:200149","Helen Sheedy"}
	{"INA","wta:200165","Lany Kaligis"}
]


Struct field names in players column:
List(Struct({'country': String, 'id': String, 'name': String}))


Sources structure:
List(Struct({'key': String, 'source_match_id': String}))

Sample sources:
shape: (3,)
Series: 'sources' [list[struct[2]]]
[
	[{"sackmann","1968-1226:1"}]
	[{"sackmann","1968-1226:2"}]
	[{"sackmann","1968-1226:3"}]
]

In [17]:
# Create a concise matches DataFrame with all relevant information
# Extract player details and match results clearly

matches_clean = matches_full.with_columns([
    # Extract player 1 (first player in the list)
    pl.col("players").list.get(0).struct.field("id").alias("player1_id"),
    pl.col("players").list.get(0).struct.field("name").alias("player1_name"),
    pl.col("players").list.get(0).struct.field("country").alias("player1_country"),
    
    # Extract player 2 (second player in the list)
    pl.col("players").list.get(1).struct.field("id").alias("player2_id"),
    pl.col("players").list.get(1).struct.field("name").alias("player2_name"),
    pl.col("players").list.get(1).struct.field("country").alias("player2_country"),
    
    # Convert start_date to timestamp
    pl.col("start_date").str.to_date().alias("date"),
    
    # Determine winner (1 if player1 won, 2 if player2 won)
    pl.when(pl.col("winner_id") == pl.col("players").list.get(0).struct.field("id"))
      .then(1)
      .when(pl.col("winner_id") == pl.col("players").list.get(1).struct.field("id"))
      .then(2)
      .otherwise(None)
      .alias("winner"),
    
    # Extract source information
    pl.col("sources").list.get(0).struct.field("key").alias("source_provider"),
    pl.col("sources").list.get(0).struct.field("source_match_id").alias("source_match_ref"),
]).select([
    # Tournament info
    pl.col("tour"),
    pl.col("name").alias("tournament"),
    pl.col("level").alias("tier"),
    pl.col("surface"),
    pl.col("year"),
    pl.col("date"),
    
    # Match info
    pl.col("round"),
    pl.col("discipline").alias("event_type"),
    pl.col("draw"),
    
    # Player 1
    pl.col("player1_id"),
    pl.col("player1_name"),
    pl.col("player1_country"),
    
    # Player 2
    pl.col("player2_id"),
    pl.col("player2_name"),
    pl.col("player2_country"),
    
    # Result
    pl.col("winner"),
    pl.col("score"),
    pl.col("status").alias("match_state"),
    
    # Source info
    pl.col("match_id").alias("source_match_id"),
    pl.col("id").alias("source_tournament_id"),
    pl.col("source_provider"),
    pl.col("source_match_ref"),
    pl.col("source_file"),
])

print(f"Clean matches DataFrame shape: {matches_clean.shape}")
print(f"\nColumns: {matches_clean.columns}")
matches_clean.head()

Clean matches DataFrame shape: (164299, 23)

Columns: ['tour', 'tournament', 'tier', 'surface', 'year', 'date', 'round', 'event_type', 'draw', 'player1_id', 'player1_name', 'player1_country', 'player2_id', 'player2_name', 'player2_country', 'winner', 'score', 'match_state', 'source_match_id', 'source_tournament_id', 'source_provider', 'source_match_ref', 'source_file']

shape: (5, 23)
┌──────┬────────────┬──────┬─────────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ tour ┆ tournament ┆ tier ┆ surface ┆ … ┆ source_tourn ┆ source_provi ┆ source_matc ┆ source_file │
│ ---  ┆ ---        ┆ ---  ┆ ---     ┆   ┆ ament_id     ┆ der          ┆ h_ref       ┆ ---         │
│ str  ┆ str        ┆ str  ┆ str     ┆   ┆ ---          ┆ ---          ┆ ---         ┆ str         │
│      ┆            ┆      ┆         ┆   ┆ str          ┆ str          ┆ str         ┆             │
╞══════╪════════════╪══════╪═════════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ wta  ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ sackmann:wta ┆ sackmann     ┆ 1968-1226:1 ┆ matches/wta │
│      ┆            ┆      ┆         ┆   ┆ :1968-1226   ┆              ┆             ┆ /1968/adela │
│      ┆            ┆      ┆         ┆   ┆              ┆              ┆             ┆ ide/main…   │
│ wta  ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ sackmann:wta ┆ sackmann     ┆ 1968-1226:2 ┆ matches/wta │
│      ┆            ┆      ┆         ┆   ┆ :1968-1226   ┆              ┆             ┆ /1968/adela │
│      ┆            ┆      ┆         ┆   ┆              ┆              ┆             ┆ ide/main…   │
│ wta  ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ sackmann:wta ┆ sackmann     ┆ 1968-1226:3 ┆ matches/wta │
│      ┆            ┆      ┆         ┆   ┆ :1968-1226   ┆              ┆             ┆ /1968/adela │
│      ┆            ┆      ┆         ┆   ┆              ┆              ┆             ┆ ide/main…   │
│ wta  ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ sackmann:wta ┆ sackmann     ┆ 1968-1226:4 ┆ matches/wta │
│      ┆            ┆      ┆         ┆   ┆ :1968-1226   ┆              ┆             ┆ /1968/adela │
│      ┆            ┆      ┆         ┆   ┆              ┆              ┆             ┆ ide/main…   │
│ wta  ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ sackmann:wta ┆ sackmann     ┆ 1968-1226:5 ┆ matches/wta │
│      ┆            ┆      ┆         ┆   ┆ :1968-1226   ┆              ┆             ┆ /1968/adela │
│      ┆            ┆      ┆         ┆   ┆              ┆              ┆             ┆ ide/main…   │
└──────┴────────────┴──────┴─────────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [18]:
# Summary of the clean matches DataFrame
print("=== Clean Matches DataFrame Summary ===")
print(f"Total matches: {matches_clean.height:,}")
print(f"\nColumns ({len(matches_clean.columns)} total):")
for i, col in enumerate(matches_clean.columns, 1):
    print(f"  {i:2d}. {col}")

print("\n=== Sample Data ===")
print(matches_clean.select([
    "date", "tournament", "tier", "surface", "round",
    "player1_name", "player2_name", "winner", "score"
]).head(10))

=== Clean Matches DataFrame Summary ===
Total matches: 164,299

Columns (23 total):
   1. tour
   2. tournament
   3. tier
   4. surface
   5. year
   6. date
   7. round
   8. event_type
   9. draw
  10. player1_id
  11. player1_name
  12. player1_country
  13. player2_id
  14. player2_name
  15. player2_country
  16. winner
  17. score
  18. match_state
  19. source_match_id
  20. source_tournament_id
  21. source_provider
  22. source_match_ref
  23. source_file

=== Sample Data ===
shape: (10, 9)
┌────────────┬────────────┬──────┬─────────┬───┬──────────────┬─────────────┬────────┬─────────────┐
│ date       ┆ tournament ┆ tier ┆ surface ┆ … ┆ player1_name ┆ player2_nam ┆ winner ┆ score       │
│ ---        ┆ ---        ┆ ---  ┆ ---     ┆   ┆ ---          ┆ e           ┆ ---    ┆ ---         │
│ date       ┆ str        ┆ str  ┆ str     ┆   ┆ str          ┆ ---         ┆ i32    ┆ str         │
│            ┆            ┆      ┆         ┆   ┆              ┆ str         ┆        ┆             │
╞════════════╪════════════╪══════╪═════════╪═══╪══════════════╪═════════════╪════════╪═════════════╡
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Lita Liem    ┆ Cynthia     ┆ 1      ┆ 4-6 6-3 6-3 │
│            ┆            ┆      ┆         ┆   ┆              ┆ Doerner     ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Vicki        ┆ Barbara     ┆ 1      ┆ 6-3 5-7 6-3 │
│            ┆            ┆      ┆         ┆   ┆ Lancaster    ┆ Walsh       ┆        ┆             │
│            ┆            ┆      ┆         ┆   ┆ Kerr         ┆             ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Helen Sheedy ┆ Lany        ┆ 1      ┆ 6-1 1-6 7-5 │
│            ┆            ┆      ┆         ┆   ┆              ┆ Kaligis     ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Karen        ┆ Lita Liem   ┆ 1      ┆ 6-0 6-1     │
│            ┆            ┆      ┆         ┆   ┆ Krantzcke    ┆             ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Helen Amos   ┆ Vicki       ┆ 1      ┆ 6-2 6-1     │
│            ┆            ┆      ┆         ┆   ┆              ┆ Lancaster   ┆        ┆             │
│            ┆            ┆      ┆         ┆   ┆              ┆ Kerr        ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Lesley Hunt  ┆ Helen       ┆ 1      ┆ 6-0 6-0     │
│            ┆            ┆      ┆         ┆   ┆              ┆ Sheedy      ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Kerry Harris ┆ Janine      ┆ 1      ┆ 6-3 6-2     │
│            ┆            ┆      ┆         ┆   ┆              ┆ Whyte       ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Margaret     ┆ Frances     ┆ 1      ┆ 8-6 1-6 6-1 │
│            ┆            ┆      ┆         ┆   ┆ Dunn         ┆ Luff        ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Karen        ┆ Helen Amos  ┆ 1      ┆ 9-7 6-2     │
│            ┆            ┆      ┆         ┆   ┆ Krantzcke    ┆             ┆        ┆             │
│ 1968-11-23 ┆ Adelaide   ┆ W    ┆ Grass   ┆ … ┆ Kerry Reid   ┆ Judith Gohl ┆ 1      ┆ 6-0 6-4     │
└────────────┴────────────┴──────┴─────────┴───┴──────────────┴─────────────┴────────┴─────────────┘

In [ ]:
matches_clean.tail(10)

In [10]:
# 4. Top tournaments by match count
print("=== Top 20 Tournaments by Match Count ===")
tournament_counts = matches_full.group_by("name").agg(pl.count()).sort("count", descending=True).head(20)
print(tournament_counts)

# 5. Match status distribution
print("\n=== Match Status Distribution ===")
status_counts = matches_full.group_by("status").agg(pl.count()).sort("count", descending=True)
print(status_counts)

=== Top 20 Tournaments by Match Count ===
shape: (20, 2)
┌─────────────────┬───────┐
│ name            ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ Wimbledon       ┆ 6759  │
│ Roland Garros   ┆ 6621  │
│ Australian Open ┆ 5928  │
│ US Open         ┆ 5830  │
│ Indian Wells    ┆ 2924  │
│ …               ┆ …     │
│ Cincinnati      ┆ 1427  │
│ Charleston      ┆ 1382  │
│ Tokyo           ┆ 1358  │
│ Auckland        ┆ 1355  │
│ San Diego       ┆ 1314  │
└─────────────────┴───────┘

=== Match Status Distribution ===
shape: (2, 2)
┌───────────┬────────┐
│ status    ┆ count  │
│ ---       ┆ ---    │
│ str       ┆ u32    │
╞═══════════╪════════╡
│ completed ┆ 163022 │
│ walkover  ┆ 1277   │
└───────────┴────────┘

/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/1305167727.py:3: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  tournament_counts = matches_full.group_by("name").agg(pl.count()).sort("count", descending=True).head(20)
/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/1305167727.py:8: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  status_counts = matches_full.group_by("status").agg(pl.count()).sort("count", descending=True)

In [9]:
# Quick analysis of the matches data

# 1. Matches by year
print("=== Matches by Year ===")
yearly_counts = matches_full.group_by("year").agg(pl.count()).sort("year")
print(yearly_counts)

# 2. Matches by surface
print("\n=== Matches by Surface ===")
surface_counts = matches_full.group_by("surface").agg(pl.count()).sort("count", descending=True)
print(surface_counts)

# 3. Matches by tournament level
print("\n=== Matches by Tournament Level ===")
level_counts = matches_full.group_by("level").agg(pl.count()).sort("count", descending=True)
print(level_counts)

=== Matches by Year ===
shape: (59, 2)
┌──────┬───────┐
│ year ┆ count │
│ ---  ┆ ---   │
│ i64  ┆ u32   │
╞══════╪═══════╡
│ 1968 ┆ 3068  │
│ 1969 ┆ 3024  │
│ 1970 ┆ 3046  │
│ 1971 ┆ 2580  │
│ 1972 ┆ 2996  │
│ …    ┆ …     │
│ 2022 ┆ 2594  │
│ 2023 ┆ 2810  │
│ 2024 ┆ 2689  │
│ 2025 ┆ 2795  │
│ 2026 ┆ 3458  │
└──────┴───────┘

=== Matches by Surface ===
shape: (6, 2)
┌─────────┬───────┐
│ surface ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ Hard    ┆ 68594 │
│ Clay    ┆ 50933 │
│ Grass   ┆ 23556 │
│ Carpet  ┆ 14094 │
│ null    ┆ 7060  │
│ clay    ┆ 62    │
└─────────┴───────┘

=== Matches by Tournament Level ===
shape: (19, 2)
┌───────┬───────┐
│ level ┆ count │
│ ---   ┆ ---   │
│ str   ┆ u32   │
╞═══════╪═══════╡
│ W     ┆ 70077 │
│ G     ┆ 26007 │
│ I     ┆ 15872 │
│ D     ┆ 12245 │
│ P     ┆ 11142 │
│ …     ┆ …     │
│ F     ┆ 533   │
│ E     ┆ 282   │
│ 50+H  ┆ 184   │
│ 35+H  ┆ 31    │
│ J     ┆ 6     │
└───────┴───────┘

/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/2045479671.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  yearly_counts = matches_full.group_by("year").agg(pl.count()).sort("year")
/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/2045479671.py:10: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  surface_counts = matches_full.group_by("surface").agg(pl.count()).sort("count", descending=True)
/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/2045479671.py:15: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  level_counts = matches_full.group_by("level").agg(pl.count()).sort("count", descending=True)

In [6]:
# Unnest the matches into a proper DataFrame
# The matches column contains structs with 'tournament' and 'match' fields

matches_df = df.select(pl.col("matches").explode()).unnest("matches")
print(f"Matches DataFrame shape: {matches_df.shape}")
print(f"\nColumns: {matches_df.columns}")
matches_df.head()

Matches DataFrame shape: (164299, 3)

Columns: ['event', 'match', 'source_file']

/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/1428985696.py:4: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  matches_df = df.select(pl.col("matches").explode()).unnest("matches")

shape: (5, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ event                          ┆ match                          ┆ source_file                    │
│ ---                            ┆ ---                            ┆ ---                            │
│ struct[9]                      ┆ struct[10]                     ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ {"singles","main","sackmann:wt ┆ {null,null,"wta-90ca897edce71c ┆ matches/wta/1968/adelaide/main │
│ …                              ┆ …                              ┆ …                              │
│ {"singles","main","sackmann:wt ┆ {null,null,"wta-3ed8c4e6463af4 ┆ matches/wta/1968/adelaide/main │
│ …                              ┆ …                              ┆ …                              │
│ {"singles","main","sackmann:wt ┆ {null,null,"wta-8146965e3f66b6 ┆ matches/wta/1968/adelaide/main │
│ …                              ┆ …                              ┆ …                              │
│ {"singles","main","sackmann:wt ┆ {null,null,"wta-0ddb7592595412 ┆ matches/wta/1968/adelaide/main │
│ …                              ┆ …                              ┆ …                              │
│ {"singles","main","sackmann:wt ┆ {null,null,"wta-4aeeed9511bb38 ┆ matches/wta/1968/adelaide/main │
│ …                              ┆ …                              ┆ …                              │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

In [5]:
# The data is nested - let's explore the structure
# The 'matches' column contains a list of match structs

# First, let's unnest the matches to see the actual match data
matches_list = df["matches"].explode()
print(f"Total matches: {matches_list.len()}")
print(f"\nMatch structure:")
print(matches_list.head(3))

Total matches: 164299

Match structure:
shape: (3,)
Series: 'matches' [struct[3]]
[
	{{"singles","main","sackmann:wta:1968-1226","W","Adelaide","1968-11-23","Grass","wta",1968},{null,null,"wta-90ca897edce71c76d381",null,[{"INA","wta:200139","Lita Liem"}, {"AUS","wta:200146","Cynthia Doerner"}],"R32","4-6 6-3 6-3",[{"sackmann","1968-1226:1"}],"completed","wta:200139"},"matches/wta/1968/adelaide/main-singles.json"}
	{{"singles","main","sackmann:wta:1968-1226","W","Adelaide","1968-11-23","Grass","wta",1968},{null,null,"wta-3ed8c4e6463af4615f70",null,[{"AUS","wta:200203","Vicki Lancaster Kerr"}, {"AUS","wta:216624","Barbara Walsh"}],"R32","6-3 5-7 6-3",[{"sackmann","1968-1226:2"}],"completed","wta:200203"},"matches/wta/1968/adelaide/main-singles.json"}
	{{"singles","main","sackmann:wta:1968-1226","W","Adelaide","1968-11-23","Grass","wta",1968},{null,null,"wta-8146965e3f66b653283b",null,[{"AUS","wta:200149","Helen Sheedy"}, {"INA","wta:200165","Lany Kaligis"}],"R32","6-1 1-6 7-5",[{"sackmann","1968-1226:3"}],"completed","wta:200149"},"matches/wta/1968/adelaide/main-singles.json"}
]

/var/folders/76/sv22wlqx51l_7wpcjlt9ds2c0000gn/T/ipykernel_84989/4032350941.py:5: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  matches_list = df["matches"].explode()